server:
  port: 8080

mybatis-plus:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  check-config-location: true
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  data:
    redis:
      database: 0 #redis数据库索引，默认为0
      host: 127.0.0.1 #redis服务器地址
      port: 6379 #redis服务器连接端口
      password: #redis服务器连接密码，默认为null
      timeout: 5000 #redis连接超时时间
logging:
  pattern:
    level: debug
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr([%L]) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

config:
  jwt:
    secret: lyyAdmin123
    header: token
    expire: 3600
