server:
  port: 8090

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.100:4000/test?useUnicode=true&characterEncoding=utf-8
    password: SMtRoBJh
    username: root
  redis:
    database: 0 #redis数据库索引，默认为0
    host: 127.0.0.1 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password: #redis服务器连接密码，默认为null
    timeout: 5000 #redis连接超时时间
